/* ============================================
   鳞光屿 Linguang Island - 站点数据
   商品、分类数据（供详情页、搜索、相关推荐使用）
   ============================================ */

var SITE_DATA = {
  products: [
    {
      id: 1,
      title: '鳞光系列手工编织羊毛围巾 · 落日橙',
      category: 'knit',
      categoryName: '编织手作',
      series: '鳞光系列',
      price: 159,
      originalPrice: 199,
      discountTag: '限时8折',
      rating: 4.9,
      reviewCount: 128,
      soldCount: 356,
      sku: 'LGY-KNIT-001',
      material: '100%美利奴羊毛',
      craftsman: '阿屿工作室',
      leadTime: '现货 / 定制款7-14天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '限时8折',
      image: 'works/01.jpg',
      images: ['works/01.jpg', 'works/2268b798a21c0e05ef286d9afd40e5c9.jpg', 'works/619c97d61443beddd12c92ac28e90652.jpg', 'works/bb00b02b5263fa20c3def9e0ed3501d4.jpg'],
      desc: '鳞光系列手工编织羊毛围巾，采用内蒙古优质美利奴羊毛，由独立手作人一针一线手工编织而成。落日橙配色温暖治愈，鱼鳞纹编织肌理独特，每一条都有细微差异，真正的独一无二。柔软亲肤，保暖透气，是秋冬季节的完美搭配。',
      colors: ['落日橙', '薄荷绿', '雾霾蓝', '燕麦米'],
      sizes: ['标准款 180×30cm', '加长款 220×35cm', '儿童款 120×25cm'],
      intro: [
        '<p><strong>关于鳞光系列</strong></p>',
        '<p>鳞光系列的灵感来源于夕阳下波光粼粼的湖面。手作人阿屿将这一瞬间的美好凝固在毛线的纹理中，每一针每一线都承载着对自然之美的敬意。</p>',
        '<p>鱼鳞纹编织技法是本系列的核心特色。通过特殊的针法组合，在织物表面形成如同鱼鳞般错落有致的肌理，在光线下呈现出微妙的光泽变化，正如湖面闪烁的鳞光。</p>',
        '<p><strong>材质说明</strong></p>',
        '<p>选用内蒙古鄂尔多斯草原优质美利奴羊毛，纤维细度18.5微米，长度超过70mm。经过严格的洗毛、梳毛、纺纱工序，最终纺成2/48Nm的高品质毛线。羊毛具有天然的卷曲弹性，保暖性是普通棉纤维的3倍，同时具备优异的透气性和吸湿性。</p>',
        '<p><strong>手作过程</strong></p>',
        '<p>每一条围巾都由阿屿工作室的手作人手工编织完成。从起针到收针，一条标准款围巾需要约15,000针，耗时约18-22小时。由于纯手工制作，每一条围巾的纹理疏密、颜色深浅都会有细微差异，这正是手作的魅力所在——每一件都是独一无二的。</p>',
        '<p><strong>护理建议</strong></p>',
        '<p>建议手洗或干洗，使用中性羊毛洗涤剂，水温不超过30°C。洗涤后平铺阴干，避免悬挂变形。存放时可放置防虫剂，长期不使用时建议密封保存。</p>'
      ],
      specRows: [
        ['商品名称', '鳞光系列手工编织羊毛围巾 · 落日橙'],
        ['商品编号', 'LGY-KNIT-001'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '鳞光系列'],
        ['材质', '100%美利奴羊毛'],
        ['纤维细度', '18.5微米'],
        ['毛线规格', '2/48Nm'],
        ['标准款尺寸', '180cm × 30cm'],
        ['加长款尺寸', '220cm × 35cm'],
        ['儿童款尺寸', '120cm × 25cm'],
        ['重量', '约180g（标准款）'],
        ['编织针法', '鱼鳞纹手工编织'],
        ['制作方式', '纯手工编织'],
        ['制作周期', '现货48小时发货 / 定制7-14天'],
        ['可选颜色', '落日橙、薄荷绿、雾霾蓝、燕麦米'],
        ['洗涤方式', '手洗/干洗，水温≤30°C'],
        ['产地', '中国 · 武汉'],
        ['手作人', '阿屿工作室']
      ],
      videoTitle: '一针一线见匠心 · 围巾手作全过程',
      videoSubtitle: '时长 3:28 · 记录从选纱到成品的蜕变',
      pdfName: '鳞光系列羊毛围巾 · 作品手册.pdf'
    },
    {
      id: 2,
      title: '屿系列手工陶瓷马克杯 · 粗陶釉色',
      category: 'ceramic',
      categoryName: '陶艺器皿',
      series: '屿系列',
      price: 128,
      originalPrice: 0,
      discountTag: '',
      rating: 4.8,
      reviewCount: 96,
      soldCount: 210,
      sku: 'LGY-CER-002',
      material: '粗陶 / 天然矿物釉',
      craftsman: '陶野工作室',
      leadTime: '现货 / 定制款10-15天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '新品',
      image: 'works/054cdf0217a93ebdaa423b9df954e02b.jpg',
      images: ['works/054cdf0217a93ebdaa423b9df954e02b.jpg', 'works/23e4ec383b1816b4c98a01805032002c.jpg', 'works/7c3fb1a2e72453e287ca65e6157a7eb2.jpg', 'works/cf58732337ca917d606f964128ad6c54.jpg'],
      desc: '屿系列手工陶瓷马克杯，采用高白粗陶泥手工拉坯成型，天然矿物釉烧制。粗陶釉色温润质朴，杯身保留手作肌理，握感舒适。每一只杯子都因窑变而独一无二，是日常茶饮的理想伴侣。',
      colors: ['粗陶本色', '墨灰', '米白'],
      sizes: ['标准杯 350ml', '大容量 500ml'],
      intro: [
        '<p><strong>关于屿系列</strong></p>',
        '<p>屿系列以"岛屿与海浪"为灵感，将粗陶质朴的质感与自然釉色相融合。每一只杯子都由陶野工作室的手作人手工拉坯、修坯、上釉，经过高温窑烧而成。</p>',
        '<p><strong>材质工艺</strong></p>',
        '<p>选用高白粗陶泥，天然矿物釉料，1300°C高温还原烧制。釉面温润，胎体厚重，具有良好的保温性能。手工制品会保留细微的手作痕迹，这正是每一件的独特之处。</p>',
        '<p><strong>使用与养护</strong></p>',
        '<p>可用于微波炉与洗碗机。避免骤冷骤热，使用后及时清洗晾干。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列手工陶瓷马克杯 · 粗陶釉色'],
        ['商品编号', 'LGY-CER-002'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', '粗陶 / 天然矿物釉'],
        ['容量', '标准杯 350ml / 大容量 500ml'],
        ['烧制温度', '1300°C 还原烧'],
        ['制作方式', '手工拉坯 · 手工上釉'],
        ['制作周期', '现货48小时发货 / 定制10-15天'],
        ['可选颜色', '粗陶本色、墨灰、米白'],
        ['产地', '中国 · 武汉'],
        ['手作人', '陶野工作室']
      ],
      videoTitle: '从泥到器 · 马克杯手作全过程',
      videoSubtitle: '时长 4:12 · 记录拉坯、修坯、上釉与窑烧',
      pdfName: '屿系列陶瓷马克杯 · 作品手册.pdf'
    },
    {
      id: 3,
      title: '手工缝制头层牛皮短款钱包 · 复古棕',
      category: 'leather',
      categoryName: '皮具手作',
      series: '屿系列',
      price: 268,
      originalPrice: 0,
      discountTag: '',
      rating: 4.9,
      reviewCount: 74,
      soldCount: 158,
      sku: 'LGY-LEA-003',
      material: '意大利头层植鞣牛皮',
      craftsman: '匠造皮艺工作室',
      leadTime: '定制款7-10天',
      delivery: '顺丰包邮 · 发货后3-5天送达',
      tag: '',
      image: 'works/069d8d57722f1eefb7612235d0c92d77.jpg',
      images: ['works/069d8d57722f1eefb7612235d0c92d77.jpg', 'works/3741f565dfd39f4d616d1eac8edfc7b6.jpg', 'works/842b7d997cb33d133d117e4fcee05f9e.jpg', 'works/e13f04f0b526c0bc4e1df464b4d01ed4.jpg'],
      desc: '手工缝制头层牛皮短款钱包，采用意大利头层植鞣牛皮，传统马鞍缝线工艺手工制作。复古棕色随使用时间愈发温润有光泽，越用越有味道。多卡位设计，日常通勤与旅行皆宜。',
      colors: ['复古棕', '焦糖色', '黑色'],
      sizes: ['短款', '长款'],
      intro: [
        '<p><strong>关于这件皮具</strong></p>',
        '<p>精选意大利头层植鞣牛皮，皮面天然、环保，随使用与光照逐渐氧化，颜色愈发深沉温润，形成独一无二的岁月痕迹。</p>',
        '<p><strong>手工工艺</strong></p>',
        '<p>采用传统马鞍缝线工艺，双针双线手工缝制，牢固耐用；边缘手工打磨封边，细节考究。每一处针脚都是匠心的见证。</p>',
        '<p><strong>养护建议</strong></p>',
        '<p>避免暴晒与潮湿，定期使用貂油或皮革护理油保养，可长久保持光泽。</p>'
      ],
      specRows: [
        ['商品名称', '手工缝制头层牛皮短款钱包 · 复古棕'],
        ['商品编号', 'LGY-LEA-003'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['材质', '意大利头层植鞣牛皮'],
        ['工艺', '马鞍缝线 · 手工封边'],
        ['卡位', '8卡位 + 2钞位 + 1零钱位'],
        ['制作周期', '定制款7-10天'],
        ['可选颜色', '复古棕、焦糖色、黑色'],
        ['产地', '中国 · 武汉'],
        ['手作人', '匠造皮艺工作室']
      ],
      videoTitle: '一针一线 · 皮具手作全过程',
      videoSubtitle: '时长 5:02 · 记录裁皮、缝线、封边',
      pdfName: '头层牛皮短款钱包 · 作品手册.pdf'
    },
    {
      id: 4,
      title: '四季香薰大豆蜡蜡烛礼盒套装 · 3支装',
      category: 'candle',
      categoryName: '香薰蜡烛',
      series: '四季系列',
      price: 198,
      originalPrice: 268,
      discountTag: '买二送一',
      rating: 4.9,
      reviewCount: 187,
      soldCount: 402,
      sku: 'LGY-CND-004',
      material: '天然大豆蜡 / 植物精油',
      craftsman: '屿香工作室',
      leadTime: '现货',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '买二送一',
      image: 'works/1fd205de11f5d47ad83b0c7072961576.jpg',
      images: ['works/1fd205de11f5d47ad83b0c7072961576.jpg', 'works/48fcea0ed9cd00772e2aa7fb1bb7dbb3.jpg', 'works/a71a90dca36579b41915bfc6e600b539.jpg', 'works/ee13552d8581cd8f6e0346bad0646920.jpg'],
      desc: '四季香薰大豆蜡蜡烛礼盒套装，精选天然大豆蜡与植物精油调配，春樱、夏荷、秋桂、冬梅四季香型。燃烧纯净无黑烟，香气温和持久。礼盒包装精美，自用或送礼皆宜。',
      colors: ['四季套装'],
      sizes: ['3支装', '6支装'],
      intro: [
        '<p><strong>四季香型</strong></p>',
        '<p>春樱（樱花·白桃）、夏荷（睡莲·青瓜）、秋桂（桂花·雪梨）、冬梅（白梅·松木），四款香型还原四季气息。</p>',
        '<p><strong>天然材质</strong></p>',
        '<p>采用天然大豆蜡与棉芯，燃烧时间更持久、更环保。植物精油来自全球优质产地，香气天然纯净。</p>',
        '<p><strong>使用建议</strong></p>',
        '<p>首次点燃建议燃烧2小时以上，让蜡面均匀融化，避免记忆坑。</p>'
      ],
      specRows: [
        ['商品名称', '四季香薰大豆蜡蜡烛礼盒套装 · 3支装'],
        ['商品编号', 'LGY-CND-004'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '四季系列'],
        ['材质', '天然大豆蜡 / 植物精油'],
        ['规格', '3支装 / 6支装'],
        ['香型', '春樱、夏荷、秋桂、冬梅'],
        ['燃烧时长', '约25-30小时/支'],
        ['制作周期', '现货'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿香工作室']
      ],
      videoTitle: '一盏烛光 · 香薰蜡烛手作过程',
      videoSubtitle: '时长 3:45 · 记录蜡材融化、调香与灌装',
      pdfName: '四季香薰蜡烛礼盒 · 作品手册.pdf'
    },
    {
      id: 5,
      title: '鳞光系列925银手工耳环 · 星月',
      category: 'jewelry',
      categoryName: '手工饰品',
      series: '鳞光系列',
      price: 188,
      originalPrice: 0,
      discountTag: '',
      rating: 4.8,
      reviewCount: 45,
      soldCount: 96,
      sku: 'LGY-JWL-005',
      material: '925纯银 / 天然锆石',
      craftsman: '屿银工作室',
      leadTime: '现货 / 定制款7天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: 'NEW',
      image: 'works/2268b798a21c0e05ef286d9afd40e5c9.jpg',
      images: ['works/2268b798a21c0e05ef286d9afd40e5c9.jpg', 'works/619c97d61443beddd12c92ac28e90652.jpg', 'works/bb00b02b5263fa20c3def9e0ed3501d4.jpg', 'works/01.jpg'],
      desc: '鳞光系列925银手工耳环，以星月为灵感，采用925纯银手工锻造。星月造型简约灵动，天然锆石点缀微光。手工打磨的银面温润细腻，佩戴轻盈，日常或通勤皆宜。',
      colors: ['银色', '镀金'],
      sizes: ['单只装', '对装'],
      intro: [
        '<p><strong>设计灵感</strong></p>',
        '<p>星月主题取自夜空中的点点鳞光，将星辰与月牙的意象融入银饰设计中，简约而不失灵动。</p>',
        '<p><strong>材质工艺</strong></p>',
        '<p>采用S925纯银手工锻造，锆石爪镶工艺，银面手工打磨至温润光泽。可日常佩戴，不易过敏。</p>',
        '<p><strong>保养建议</strong></p>',
        '<p>避免接触化妆品与香水，佩戴后擦拭密封保存。银饰氧化发黑属正常现象，可用擦银布清洁。</p>'
      ],
      specRows: [
        ['商品名称', '鳞光系列925银手工耳环 · 星月'],
        ['商品编号', 'LGY-JWL-005'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '鳞光系列'],
        ['材质', 'S925纯银 / 天然锆石'],
        ['工艺', '手工锻造 · 爪镶'],
        ['规格', '单只装 / 对装'],
        ['制作周期', '现货 / 定制7天'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿银工作室']
      ],
      videoTitle: '指尖微光 · 银饰手作过程',
      videoSubtitle: '时长 4:30 · 记录锻造、镶嵌与打磨',
      pdfName: '925银星月耳环 · 作品手册.pdf'
    },
    {
      id: 6,
      title: '屿系列手工缝线手账本套装 · 含文具',
      category: 'stationery',
      categoryName: '手账文具',
      series: '屿系列',
      price: 156,
      originalPrice: 0,
      discountTag: '',
      rating: 4.7,
      reviewCount: 63,
      soldCount: 132,
      sku: 'LGY-STA-006',
      material: '进口布面 / 100g道林纸',
      craftsman: '屿纸工作室',
      leadTime: '现货',
      delivery: '中通包邮 · 48小时内发货',
      tag: '',
      image: 'works/23e4ec383b1816b4c98a01805032002c.jpg',
      images: ['works/23e4ec383b1816b4c98a01805032002c.jpg', 'works/7c3fb1a2e72453e287ca65e6157a7eb2.jpg', 'works/cf58732337ca917d606f964128ad6c54.jpg', 'works/054cdf0217a93ebdaa423b9df954e02b.jpg'],
      desc: '屿系列手工缝线手账本套装，进口布面手工装订，内页采用100g道林纸，书写顺滑不洇墨。包含手账本、纸胶带与金属书签，是记录生活的美好伙伴。',
      colors: ['雾霾蓝', '燕麦米', '薄荷绿'],
      sizes: ['A5', 'B6'],
      intro: [
        '<p><strong>关于本子</strong></p>',
        '<p>手工缝线装订，可180°平摊书写。进口布面手感细腻，耐磨耐脏，陪伴你记录每一天的点滴。</p>',
        '<p><strong>内页纸张</strong></p>',
        '<p>100g道林纸，米白护眼，书写顺滑，适合钢笔、中性笔与荧光笔。附赠纸胶带与金属书签。</p>',
        '<p><strong>使用建议</strong></p>',
        '<p>可用于手账、日记、旅行记录与计划管理，让记录成为享受。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列手工缝线手账本套装 · 含文具'],
        ['商品编号', 'LGY-STA-006'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['封面材质', '进口布面'],
        ['内页', '100g道林纸 · 176页'],
        ['规格', 'A5 / B6'],
        ['套装内容', '手账本 + 纸胶带 + 金属书签'],
        ['制作周期', '现货'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿纸工作室']
      ],
      videoTitle: '记录生活 · 手账本手作过程',
      videoSubtitle: '时长 3:20 · 记录选纸、缝线与装订',
      pdfName: '屿系列手账本套装 · 作品手册.pdf'
    },
    {
      id: 7,
      title: '手工藤编收纳花篮 · 北欧风',
      category: 'knit',
      categoryName: '编织手作',
      series: '屿系列',
      price: 128,
      originalPrice: 0,
      discountTag: '',
      rating: 4.6,
      reviewCount: 38,
      soldCount: 80,
      sku: 'LGY-BSK-007',
      material: '天然藤条 / 棉麻绳',
      craftsman: '阿屿工作室',
      leadTime: '现货 / 定制款10天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '',
      image: 'works/3741f565dfd39f4d616d1eac8edfc7b6.jpg',
      images: ['works/3741f565dfd39f4d616d1eac8edfc7b6.jpg', 'works/842b7d997cb33d133d117e4fcee05f9e.jpg', 'works/e13f04f0b526c0bc4e1df464b4d01ed4.jpg', 'works/069d8d57722f1eefb7612235d0c92d77.jpg'],
      desc: '手工藤编收纳花篮，采用天然藤条手工编织，北欧简约风。可作为收纳篮、花篮或装饰摆件，为家居增添自然的温度。手工编织使每一只花篮的纹理都略有不同。',
      colors: ['原色藤编', '米白'],
      sizes: ['小号', '中号', '大号'],
      intro: [
        '<p><strong>天然材质</strong></p>',
        '<p>精选天然藤条，经日晒、去皮、软化后手工编织，环保耐用，散发淡淡的植物清香。</p>',
        '<p><strong>手工编织</strong></p>',
        '<p>由阿屿工作室手作人逐根编织，纹理疏密有致。可作为收纳、花篮或墙面装饰，一物多用。</p>',
        '<p><strong>养护建议</strong></p>',
        '<p>避免长时间暴晒与潮湿，如有灰尘可用软毛刷轻扫。</p>'
      ],
      specRows: [
        ['商品名称', '手工藤编收纳花篮 · 北欧风'],
        ['商品编号', 'LGY-BSK-007'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', '天然藤条 / 棉麻绳'],
        ['规格', '小号 / 中号 / 大号'],
        ['制作方式', '纯手工编织'],
        ['制作周期', '现货 / 定制10天'],
        ['产地', '中国 · 武汉'],
        ['手作人', '阿屿工作室']
      ],
      videoTitle: '一藤一编 · 花篮手作过程',
      videoSubtitle: '时长 3:55 · 记录备料、编织与收边',
      pdfName: '手工藤编收纳花篮 · 作品手册.pdf'
    },
    {
      id: 8,
      title: '天然植物精油手工香皂 · 玫瑰薰衣草',
      category: 'candle',
      categoryName: '香薰蜡烛',
      series: '四季系列',
      price: 58,
      originalPrice: 78,
      discountTag: '热销',
      rating: 4.8,
      reviewCount: 152,
      soldCount: 318,
      sku: 'LGY-SOA-008',
      material: '天然植物油脂 / 精油',
      craftsman: '屿香工作室',
      leadTime: '现货',
      delivery: '中通包邮 · 48小时内发货',
      tag: '热销',
      image: 'works/48fcea0ed9cd00772e2aa7fb1bb7dbb3.jpg',
      images: ['works/48fcea0ed9cd00772e2aa7fb1bb7dbb3.jpg', 'works/a71a90dca36579b41915bfc6e600b539.jpg', 'works/ee13552d8581cd8f6e0346bad0646920.jpg', 'works/1fd205de11f5d47ad83b0c7072961576.jpg'],
      desc: '天然植物精油手工香皂，以玫瑰与薰衣草精油入皂，冷制工艺保留植物养分。泡沫细腻丰富，洗后不紧绷，带有温和的草本香气。可用于洁面与沐浴。',
      colors: ['玫瑰', '薰衣草'],
      sizes: ['单块装', '三块礼盒装'],
      intro: [
        '<p><strong>天然配方</strong></p>',
        '<p>采用冷制皂工艺，选用橄榄油、椰子油等天然植物油脂，保留甘油与植物养分。</p>',
        '<p><strong>香调</strong></p>',
        '<p>玫瑰香调馥郁温柔，薰衣草香调舒缓安神。天然植物精油，香气柔和自然。</p>',
        '<p><strong>使用建议</strong></p>',
        '<p>避光阴凉处保存，使用后放置于沥水皂托，可延长使用寿命。</p>'
      ],
      specRows: [
        ['商品名称', '天然植物精油手工香皂 · 玫瑰薰衣草'],
        ['商品编号', 'LGY-SOA-008'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '四季系列'],
        ['材质', '天然植物油脂 / 植物精油'],
        ['规格', '单块装 / 三块礼盒装'],
        ['工艺', '冷制皂'],
        ['保质期', '24个月'],
        ['制作周期', '现货'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿香工作室']
      ],
      videoTitle: '皂香四溢 · 手工皂制作过程',
      videoSubtitle: '时长 2:58 · 记录调油、搅拌与入模',
      pdfName: '天然植物精油手工香皂 · 作品手册.pdf'
    },
    {
      id: 9,
      title: '屿系列天然沉香线香 · 胡桃木',
      category: 'candle',
      categoryName: '香薰蜡烛',
      series: '屿系列',
      price: 88,
      originalPrice: 108,
      discountTag: '限时8折',
      rating: 4.7,
      reviewCount: 29,
      soldCount: 66,
      sku: 'LGY-INC-009',
      material: '天然沉香木粉 / 楠木粘粉',
      craftsman: '屿香工作室',
      leadTime: '现货',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '新品',
      image: 'works/619c97d61443beddd12c92ac28e90652.jpg',
      images: ['works/619c97d61443beddd12c92ac28e90652.jpg', 'works/bb00b02b5263fa20c3def9e0ed3501d4.jpg', 'works/01.jpg', 'works/2268b798a21c0e05ef286d9afd40e5c9.jpg'],
      desc: '屿系列天然沉香线香，精选天然沉香木粉与楠木粘粉手工搓制，古法工艺，一炷留香。胡桃木色质朴雅致，点燃后烟气清雅、香韵绵长，适合书房、茶室与静坐时使用，让空间沉淀宁静。',
      colors: ['沉香原味', '桂花香'],
      sizes: ['10g 试用装', '30g 标准装'],
      intro: [
        '<p><strong>古法手工制香</strong></p>',
        '<p>精选天然沉香木粉，按传统配方配比楠木粘粉，经手工揉制、压模、晾干而成。无化学添加，香气自然纯粹。</p>',
        '<p><strong>香韵体验</strong></p>',
        '<p>点燃后烟气清雅，沉香甜润悠长，可在书房、茶室或冥想时使用，帮助放松身心、沉淀思绪。</p>',
        '<p><strong>使用建议</strong></p>',
        '<p>请在通风处点燃，置于香插或耐火容器中，远离易燃物，熄灭后妥善存放。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列天然沉香线香 · 胡桃木'],
        ['商品编号', 'LGY-INC-009'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', '天然沉香木粉 / 楠木粘粉'],
        ['规格', '10g 试用装 / 30g 标准装'],
        ['香型', '沉香原味、桂花香'],
        ['制作方式', '古法手工制香'],
        ['制作周期', '现货'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿香工作室']
      ],
      videoTitle: '一缕烟香 · 线香制作过程',
      videoSubtitle: '时长 3:10 · 记录配粉、揉制与晾晒',
      pdfName: '屿系列沉香线香 · 作品手册.pdf'
    },
    {
      id: 10,
      title: '屿系列手工陶瓷花瓶 · 米白釉',
      category: 'ceramic',
      categoryName: '陶艺器皿',
      series: '屿系列',
      price: 168,
      originalPrice: 0,
      discountTag: '',
      rating: 4.8,
      reviewCount: 52,
      soldCount: 98,
      sku: 'LGY-CER-010',
      material: '粗陶 / 米白矿物釉',
      craftsman: '陶野工作室',
      leadTime: '现货 / 定制款10-15天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: 'NEW',
      image: 'works/7c3fb1a2e72453e287ca65e6157a7eb2.jpg',
      images: ['works/7c3fb1a2e72453e287ca65e6157a7eb2.jpg', 'works/cf58732337ca917d606f964128ad6c54.jpg', 'works/054cdf0217a93ebdaa423b9df954e02b.jpg', 'works/23e4ec383b1816b4c98a01805032002c.jpg'],
      desc: '屿系列手工陶瓷花瓶，高白粗陶泥手工拉坯，米白矿物釉高温烧制。瓶身线条圆润舒展，釉面温润如脂，自带手作肌理。插上一支干花或鲜切花，便是一隅安静的美好。',
      colors: ['米白釉', '豆青釉'],
      sizes: ['小号 15cm', '中号 22cm'],
      intro: [
        '<p><strong>关于屿系列</strong></p>',
        '<p>以"岛屿与海浪"为灵感，将粗陶质朴的质感与自然釉色相融合。每一只花瓶都由陶野工作室的手作人手工拉坯、修坯、上釉，经高温窑烧而成。</p>',
        '<p><strong>材质工艺</strong></p>',
        '<p>选用高白粗陶泥与天然矿物釉料，1300°C高温还原烧制。釉面温润，胎体厚重，可搭配干花、鲜切花或单独作为案头摆件。</p>',
        '<p><strong>使用与养护</strong></p>',
        '<p>盛水时请勿骤冷骤热，使用后及时清洗晾干，避免磕碰。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列手工陶瓷花瓶 · 米白釉'],
        ['商品编号', 'LGY-CER-010'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', '粗陶 / 米白矿物釉'],
        ['规格', '小号 15cm / 中号 22cm'],
        ['烧制温度', '1300°C 还原烧'],
        ['制作方式', '手工拉坯 · 手工上釉'],
        ['制作周期', '现货 / 定制10-15天'],
        ['可选颜色', '米白釉、豆青釉'],
        ['产地', '中国 · 武汉'],
        ['手作人', '陶野工作室']
      ],
      videoTitle: '器与花 · 陶瓷花瓶手作过程',
      videoSubtitle: '时长 4:05 · 记录拉坯、修坯、上釉与窑烧',
      pdfName: '屿系列陶瓷花瓶 · 作品手册.pdf'
    },
    {
      id: 11,
      title: '屿系列手工压花卡片 · 干花手账',
      category: 'stationery',
      categoryName: '手账文具',
      series: '屿系列',
      price: 46,
      originalPrice: 0,
      discountTag: '',
      rating: 4.6,
      reviewCount: 41,
      soldCount: 88,
      sku: 'LGY-STA-011',
      material: '进口棉纸 / 天然干花',
      craftsman: '屿纸工作室',
      leadTime: '现货',
      delivery: '中通包邮 · 48小时内发货',
      tag: '',
      image: 'works/842b7d997cb33d133d117e4fcee05f9e.jpg',
      images: ['works/842b7d997cb33d133d117e4fcee05f9e.jpg', 'works/e13f04f0b526c0bc4e1df464b4d01ed4.jpg', 'works/069d8d57722f1eefb7612235d0c92d77.jpg', 'works/3741f565dfd39f4d616d1eac8edfc7b6.jpg'],
      desc: '屿系列手工压花卡片，将真实干花小心压制在进口棉纸之间，每一张都是独一无二的自然标本。可作手账素材、书签、贺卡或桌面装饰，把四季的花叶留在纸间。',
      colors: ['干花原色', '奶油白'],
      sizes: ['单张装', '六张装'],
      intro: [
        '<p><strong>天然压花</strong></p>',
        '<p>精选当季花叶，经干燥、压制成型后封存于棉纸之间。色泽天然，纹理独一无二，每一张都是自然的印记。</p>',
        '<p><strong>手作细节</strong></p>',
        '<p>进口棉纸触感细腻，干花搭配手工排版，可用于手账拼贴、书签、贺卡或相框装饰。</p>',
        '<p><strong>使用建议</strong></p>',
        '<p>请远离潮湿与阳光直射，可长久保存。适用于书写与装饰，建议使用中性笔或铅笔书写。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列手工压花卡片 · 干花手账'],
        ['商品编号', 'LGY-STA-011'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', '进口棉纸 / 天然干花'],
        ['规格', '单张装 / 六张装'],
        ['尺寸', '约 148 × 100mm'],
        ['制作方式', '手工压制'],
        ['制作周期', '现货'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿纸工作室']
      ],
      videoTitle: '留住花叶 · 压花卡片制作过程',
      videoSubtitle: '时长 2:45 · 记录选材、压制与装裱',
      pdfName: '屿系列压花卡片 · 作品手册.pdf'
    },
    {
      id: 12,
      title: '屿系列黄铜叶片吊坠 · 鎏金',
      category: 'jewelry',
      categoryName: '手工饰品',
      series: '屿系列',
      price: 218,
      originalPrice: 268,
      discountTag: '限时8折',
      rating: 4.9,
      reviewCount: 37,
      soldCount: 54,
      sku: 'LGY-JWL-012',
      material: 'H65黄铜 / 鎏金工艺',
      craftsman: '屿银工作室',
      leadTime: '现货 / 定制款7天',
      delivery: '顺丰包邮 · 48小时内发货',
      tag: '限时8折',
      image: 'works/a71a90dca36579b41915bfc6e600b539.jpg',
      images: ['works/a71a90dca36579b41915bfc6e600b539.jpg', 'works/ee13552d8581cd8f6e0346bad0646920.jpg', 'works/1fd205de11f5d47ad83b0c7072961576.jpg', 'works/48fcea0ed9cd00772e2aa7fb1bb7dbb3.jpg'],
      desc: '屿系列黄铜叶片吊坠，以初秋的第一片银杏叶为灵感，采用H65黄铜手工锯切、打磨，鎏金工艺呈现温润光泽。叶脉纹路清晰立体，佩戴轻盈灵动，天然做旧细节更显复古质感。',
      colors: ['鎏金', '做旧银'],
      sizes: ['单件装'],
      intro: [
        '<p><strong>设计灵感</strong></p>',
        '<p>取初秋第一片落下的叶片，将自然的弧度与叶脉纹路复刻于金属之上，让时光与季节常伴身侧。</p>',
        '<p><strong>材质工艺</strong></p>',
        '<p>H65黄铜手工锯切、锤揲塑形，鎏金工艺呈现温润光泽。叶脉纹路清晰立体，佩戴轻盈，复古耐看。</p>',
        '<p><strong>保养建议</strong></p>',
        '<p>避免接触化妆品与香水，佩戴后擦拭密封保存。黄铜氧化属正常现象，可用擦银布或软布清洁恢复光泽。</p>'
      ],
      specRows: [
        ['商品名称', '屿系列黄铜叶片吊坠 · 鎏金'],
        ['商品编号', 'LGY-JWL-012'],
        ['品牌', '鳞光屿 Linguang Island'],
        ['系列', '屿系列'],
        ['材质', 'H65黄铜 / 鎏金工艺'],
        ['规格', '单件装'],
        ['工艺', '手工锯切 · 锤揲塑形'],
        ['吊坠尺寸', '约 30 × 18mm'],
        ['制作周期', '现货 / 定制7天'],
        ['产地', '中国 · 武汉'],
        ['手作人', '屿银工作室']
      ],
      videoTitle: '一片鎏金 · 黄铜吊坠手作过程',
      videoSubtitle: '时长 4:18 · 记录锯切、打磨与鎏金',
      pdfName: '屿系列黄铜叶片吊坠 · 作品手册.pdf'
    }
  ],

  // ---------- 活动信息 ----------
  events: [
    {
      id: 1,
      title: '秋日陶艺手作体验课',
      subtitle: '与泥土对话，捏出属于你的温度',
      status: '报名中',
      date: '2026年9月14日',
      dateShort: '09.14',
      month: '九月',
      day: '14',
      time: '14:00 - 17:00',
      location: '手作工坊 · 武汉市武昌区昙华林 38 号',
      price: 298,
      originalPrice: 398,
      seats: 12,
      seatsLeft: 5,
      image: 'https://aka.doubaocdn.com/s/JqZq8xlWY7',
      gallery: [
        'https://aka.doubaocdn.com/s/JqZq8xlWY7',
        'https://aka.doubaocdn.com/s/DPLsql7bUo',
        'https://aka.doubaocdn.com/s/UkgEY5dNtz',
        'https://aka.doubaocdn.com/s/KaU7Zs4Cpp',
        'https://aka.doubaocdn.com/s/Kuxq9pi7cl',
        'https://aka.doubaocdn.com/s/5MlJ2vHtOL',
        'https://aka.doubaocdn.com/s/GVBmWUfVVM',
        'https://aka.doubaocdn.com/s/4M9q2DmNYT'
      ],
      desc: '在这个秋日午后，暂时放下手机和电脑，用双手感受泥土的温度。专业陶艺老师将从揉泥、拉坯、修坯到上釉，带你完整体验一件陶器的诞生过程。无需任何基础，所有材料和工具我们都已准备好，你只需要带着好奇心来。',
      highlights: [
        { title: '专业导师全程指导', desc: '10年经验陶艺老师手把手教学，零基础也能做出满意作品' },
        { title: '完整材料包', desc: '陶土、工具、釉料全部提供，作品可带走或代烧后邮寄' },
        { title: '下午茶歇', desc: '课间提供手工点心和花草茶，在轻松氛围中交流创作' },
        { title: '作品烧制服务', desc: '现场作品可选择代烧，两周后成品邮寄到家' }
      ],
      schedule: [
        { time: '14:00', title: '签到与介绍', desc: '认识导师和同学，了解陶艺基础知识和安全须知' },
        { time: '14:20', title: '揉泥与拉坯', desc: '学习揉泥技巧，在拉坯机上体验从泥柱到器型的蜕变' },
        { time: '15:30', title: '茶歇时间', desc: '享用手工点心和花草茶，交流创作心得' },
        { time: '16:00', title: '修坯与装饰', desc: '学习修坯技巧，用刻花或捏塑装饰你的作品' },
        { time: '16:40', title: '上釉与收尾', desc: '选择釉色，完成作品最后一道工序，合影留念' }
      ],
      faqs: [
        { q: '没有任何陶艺基础可以参加吗？', a: '完全可以！课程专为零基础设计，导师会从最基础的揉泥开始教起，全程手把手指导。' },
        { q: '作品可以带走吗？', a: '现场制作的素坯可以选择带走（自然阴干），或选择代烧服务（+50元），两周后烧制完成邮寄到家。' },
        { q: '需要自带什么工具吗？', a: '所有工具和材料我们都已准备好，你只需要穿着不怕弄脏的衣服来即可。我们也提供围裙。' },
        { q: '可以退款吗？', a: '活动开始前48小时可全额退款，24-48小时内退款50%，24小时内不支持退款但可转让名额。' }
      ]
    }
  ]
};
